# Work with iridium drifting buoy data from copernicusmarine (INSITU_GLO_PHYBGCWAV_DISCRETE_MYNRT_013_030)

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from xarray import open_mfdataset
from cdm_reader_mapper import read_mdf

C:\Users\llierham\mobaxterm\.venvs\mp_py\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
ifile = "GL_TS_DB_1301529.nc"

## Open test netcdf file

In [4]:
ds = open_mfdataset(ifile)
ds

<xarray.Dataset> Size: 65kB
Dimensions:       (TIME: 1635, DEPTH: 1)
Coordinates:
  * TIME          (TIME) datetime64[ns] 13kB 2017-03-15T11:45:00 ... 2017-07-...
    LATITUDE      (TIME) float32 7kB dask.array<chunksize=(1635,), meta=np.ndarray>
    LONGITUDE     (TIME) float32 7kB dask.array<chunksize=(1635,), meta=np.ndarray>
    TRAJECTORY    |S7 7B ...
    DEPH          (DEPTH) float32 4B dask.array<chunksize=(1,), meta=np.ndarray>
Dimensions without coordinates: DEPTH
Data variables:
    TIME_QC       (TIME) float32 7kB dask.array<chunksize=(1635,), meta=np.ndarray>
    POSITION_QC   (TIME) float32 7kB dask.array<chunksize=(1635,), meta=np.ndarray>
    DC_REFERENCE  (TIME) object 13kB dask.array<chunksize=(1635,), meta=np.ndarray>
    TEMP          (TIME, DEPTH) float32 7kB dask.array<chunksize=(1635, 1), meta=np.ndarray>
    TEMP_QC       (TIME, DEPTH) float32 7kB dask.array<chunksize=(1635, 1), meta=np.ndarray>
Attributes: (12/51)
    platform_code:                  1301529
    platform_name:                  Drifting Buoy
    wmo_platform_code:              1301529
    ices_platform_code:
    coriolis_platform_code:         1301529
    comment:
    ...                             ...
    date_modified:                  2025-04-08T08:14:07Z
    history:                        2025-04-08T08:14:07Z : Creation
    publisher_email:                cmems-service@ifremer.fr
    publisher_name:                 Copernicus Marine Service
    publisher_url:                  https://marine.copernicus.eu/ http://www....
    publisher_institution:          Ifremer

## Read netCDF data as MDF DataFrame

In [5]:
db = read_mdf(
    ifile, 
    imodel="cmems",
)
db

              coordinates                                     data_variables  \
                     TIME LATITUDE  LONGITUDE TRAJECTORY DEPH        TIME_QC
0     2017-03-15 11:45:00  14.7220 -17.433800    1301529  0.0              1
1     2017-03-15 12:00:00  14.7220 -17.433800    1301529  0.0              1
2     2017-03-15 13:00:00  14.7642 -17.479000    1301529  0.0              1
3     2017-03-15 14:00:00  14.7644 -17.478800    1301529  0.0              1
4     2017-03-15 15:00:00  14.7644 -17.479000    1301529  0.0              1
...                   ...      ...        ...        ...  ...            ...
1630  2017-07-26 20:00:00  14.7624 -17.475599    1301529  0.0              1
1631  2017-07-27 05:01:00  14.7624 -17.475000    1301529  0.0              1
1632  2017-07-27 08:01:00  14.7624 -17.476000    1301529  0.0              1
1633  2017-07-27 20:00:00  14.7626 -17.475401    1301529  0.0              1
1634  2017-07-28 08:00:00  14.7616 -17.476400    1301529  0.0              1

                                                  ...       global_attributes  \
     POSITION_QC DC_REFERENCE       TEMP TEMP_QC  ...          netcdf_version
0              4   1026143280  24.690001       1  ...  netCDF-4 classic model
1              4   1026143799  26.860001       2  ...  netCDF-4 classic model
2              4   1026145330  28.040001       2  ...  netCDF-4 classic model
3              4   1026147678  27.820000       2  ...  netCDF-4 classic model
4              4   1026162787  29.670000       2  ...  netCDF-4 classic model
...          ...          ...        ...     ...  ...                     ...
1630           4   1084345827  30.129999       1  ...  netCDF-4 classic model
1631           4   1084541381  27.910000       1  ...  netCDF-4 classic model
1632           4   1084567692  27.670000       1  ...  netCDF-4 classic model
1633           4   1085266242  29.290001       1  ...  netCDF-4 classic model
1634           4   1085530868  27.500000       1  ...  netCDF-4 classic model

                                                                        \
     format_version                                        Conventions
0               2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
1               2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
2               2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
3               2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
4               2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
...             ...                                                ...
1630            2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
1631            2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
1632            2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
1633            2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....
1634            2.0  CF-1.11 Copernicus-InSituTAC-FormatManual-2.0....

                                                            \
            date_modified                          history
0     2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
1     2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
2     2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
3     2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
4     2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
...                   ...                              ...
1630  2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
1631  2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
1632  2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
1633  2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation
1634  2025-04-08 08:14:07  2025-04-08T08:14:07Z : Creation

                                                           \
               publisher_email             publisher_name
0     cmems-service@ifremer.fr  Copernicus Marine Service
1     cmems-service@ifremer.fr  Copernicus Marine Service
2     cmems-service@ifremer.fr  Copernicus Marine Service
3     cmems-service@ifremer.fr  Copernicus Marine Service
4     cmems-service@ifremer.fr  Copernicus Marine Service
...                        ...                        ...
1630  cmems-service@ifremer.fr  Copernicus Marine Service
1631  cmems-service@ifremer.fr  Copernicus Marine Service
1632  cmems-service@ifremer.fr  Copernicus Marine Service
1633  cmems-service@ifremer.fr  Copernicus Marine Service
1634  cmems-service@ifremer.fr  Copernicus Marine Service

                                                                               \
                                          publisher_url publisher_institution
0     https://marine.copernicus.eu/ http://www.marin...               Ifremer
1     https://marine.copernicus.eu/ http://www.marin...               Ifremer
2     https://marine.copernicus.eu/ http://www.marin...               Ifremer
3     https://marine.copernicus.eu/ http://www.marin...               Ifremer
4     https://marine.copernicus.eu/ http://www.marin...               Ifremer
...                                                 ...                   ...
1630  https://marine.copernicus.eu/ http://www.marin...               Ifremer
1631  https://marine.copernicus.eu/ http://www.marin...               Ifremer
1632  https://marine.copernicus.eu/ http://www.marin...               Ifremer
1633  https://marine.copernicus.eu/ http://www.marin...               Ifremer
1634  https://marine.copernicus.eu/ http://www.marin...               Ifremer

     dimensions
          NTIME
0             0
1             1
2             2
3             3
4             4
...         ...
1630       1547
1631       1548
1632       1549
1633       1550
1634       1551

[1635 rows x 60 columns]

## Map the data to the CDM

In [6]:
cdm_db = db.map_model(imodel="cmems")
cdm_db

2026-04-08 15:14:19,235 - root - INFO - Initialized basic logging configuration successfully
2026-04-08 15:14:19,915 - cdm_reader_mapper.cdm_mapper.mapper - WARNING - Missing element from input data: ('data_variables', 'ATMS')
2026-04-08 15:14:19,930 - cdm_reader_mapper.cdm_mapper.mapper - WARNING - Missing element from input data: ('data_variables', 'ATMS_QC')
2026-04-08 15:14:19,938 - cdm_reader_mapper.cdm_mapper.mapper - WARNING - Missing element from input data: ('data_variables', 'ATMS')

                      header                                     \
                   report_id region sub_region application_area
0        CMEMS-2.0-1301529-0   <NA>       <NA>   [1, 7, 10, 11]
1        CMEMS-2.0-1301529-1   <NA>       <NA>   [1, 7, 10, 11]
2        CMEMS-2.0-1301529-2   <NA>       <NA>   [1, 7, 10, 11]
3        CMEMS-2.0-1301529-3   <NA>       <NA>   [1, 7, 10, 11]
4        CMEMS-2.0-1301529-4   <NA>       <NA>   [1, 7, 10, 11]
...                      ...    ...        ...              ...
1625  CMEMS-2.0-1301529-1547   <NA>       <NA>   [1, 7, 10, 11]
1626  CMEMS-2.0-1301529-1548   <NA>       <NA>   [1, 7, 10, 11]
1627  CMEMS-2.0-1301529-1549   <NA>       <NA>   [1, 7, 10, 11]
1628  CMEMS-2.0-1301529-1550   <NA>       <NA>   [1, 7, 10, 11]
1629  CMEMS-2.0-1301529-1551   <NA>       <NA>   [1, 7, 10, 11]

                                                                              \
     observing_programme report_type station_name station_type platform_type
0                   <NA>           0         <NA>            2             5
1                   <NA>           0         <NA>            2             5
2                   <NA>           0         <NA>            2             5
3                   <NA>           0         <NA>            2             5
4                   <NA>           0         <NA>            2             5
...                  ...         ...          ...          ...           ...
1625                <NA>           0         <NA>            2             5
1626                <NA>           0         <NA>            2             5
1627                <NA>           0         <NA>            2             5
1628                <NA>           0         <NA>            2             5
1629                <NA>           0         <NA>            2             5

                        ... observations-slp                    \
     platform_sub_type  ...   original_value conversion_method
0                   69  ...             <NA>              <NA>
1                   69  ...             <NA>              <NA>
2                   69  ...             <NA>              <NA>
3                   69  ...             <NA>              <NA>
4                   69  ...             <NA>              <NA>
...                ...  ...              ...               ...
1625                69  ...             <NA>              <NA>
1626                69  ...             <NA>              <NA>
1627                69  ...             <NA>              <NA>
1628                69  ...             <NA>              <NA>
1629                69  ...             <NA>              <NA>

                                                                              \
     processing_code processing_level adjustment_id traceability advanced_qc
0                NaN             <NA>           NaN         <NA>        <NA>
1                NaN             <NA>           NaN         <NA>        <NA>
2                NaN             <NA>           NaN         <NA>        <NA>
3                NaN             <NA>           NaN         <NA>        <NA>
4                NaN             <NA>           NaN         <NA>        <NA>
...              ...              ...           ...          ...         ...
1625             NaN             <NA>           NaN         <NA>        <NA>
1626             NaN             <NA>           NaN         <NA>        <NA>
1627             NaN             <NA>           NaN         <NA>        <NA>
1628             NaN             <NA>           NaN         <NA>        <NA>
1629             NaN             <NA>           NaN         <NA>        <NA>


     advanced_uncertainty advanced_homogenisation source_id
0                    <NA>                    <NA>       NaN
1                    <NA>                    <NA>       NaN
2                    <NA>                    <NA>       NaN
3                    <NA>                    <NA>       NaN
4                    <NA>                    <NA>       NaN
...                   ...                     ...       ...
1625                 <NA>                    <NA>       NaN
1626                 <NA>                    <NA>       NaN
1627                 <NA>                    <NA>       NaN
1628                 <NA>                    <NA>       NaN
1629                 <NA>                    <NA>       NaN

[1630 rows x 365 columns]

In [7]:
cdm_db["header"]

,report_id,region,sub_region,application_area,observing_programme,report_type,station_name,station_type,platform_type,platform_sub_type,...,events_at_station,report_quality,duplicate_status,duplicates,record_timestamp,history,processing_level,processing_codes,source_id,source_record_id
0,CMEMS-2.0-1301529-0,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
1,CMEMS-2.0-1301529-1,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
2,CMEMS-2.0-1301529-2,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
3,CMEMS-2.0-1301529-3,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
4,CMEMS-2.0-1301529-4,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1625,CMEMS-2.0-1301529-1547,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
1626,CMEMS-2.0-1301529-1548,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
1627,CMEMS-2.0-1301529-1549,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
1628,CMEMS-2.0-1301529-1550,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>
1629,CMEMS-2.0-1301529-1551,<NA>,<NA>,"[1, 7, 10, 11]",<NA>,0,<NA>,2,5,69,...,<NA>,2,4,<NA>,2026-04-08 13:14:19.379522+00:00,2026-04-08 13:14:19. Initial conversion from C...,<NA>,<NA>,CMEMS-2.0,<NA>